---
title: "Chord"
description: |
  Interaction Chord Plot of CK and CKR
date: 2024-04-05
output:
  distill::distill_article:
    self_contained: false
    anchor_sections: FALSE
site: distill::distill_website
css: [styles.css]
listing: posts

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

#
## Chord Plot

Intermolecular Interactions (3 Angstrom Limit) \
Light Blue = CXCL12 \
Dark Blue = ACKR3 \


```{r chord, echo=FALSE}

library(ggraph)
library(igraph)
library(tidyverse)
library(RColorBrewer)
 
# create a data frame giving the hierarchical structure of your individuals
set.seed(1234)
d1 <- data.frame(from = "origin", to = c(rep("protein1", 68), rep("protein2", 362)))
d2 <- data.frame(from = rep(d1$to), to = paste("residue", seq(1, 430), sep = "_"))
edges <- rbind(d1, d2)
 
# create a dataframe with connection between leaves (individuals)
all_leaves <- paste("residue", seq(1, 100), sep = "_")
connect <- rbind(
  data.frame(from = c('residue_1', 'residue_1', 'residue_1', 'residue_1', 'residue_1', 'residue_1', 'residue_1', 'residue_1', 'residue_1', 'residue_2', 'residue_2', 'residue_2', 'residue_2', 'residue_3', 'residue_3', 'residue_3', 'residue_3', 'residue_4', 'residue_4', 'residue_4', 'residue_5', 'residue_5', 'residue_5', 'residue_5', 'residue_7', 'residue_7', 'residue_7', 'residue_8', 'residue_8', 'residue_8', 'residue_8', 'residue_8', 'residue_12', 'residue_12', 'residue_12', 'residue_13', 'residue_13', 'residue_13', 'residue_15', 'residue_23', 'residue_24', 'residue_24', 'residue_24', 'residue_24', 'residue_25', 'residue_25', 'residue_25', 'residue_26', 'residue_26', 'residue_26', 'residue_26', 'residue_27', 'residue_28', 'residue_28', 'residue_28', 'residue_28', 'residue_29', 'residue_29', 'residue_30', 'residue_30', 'residue_30', 'residue_30', 'residue_30', 'residue_31', 'residue_32', 'residue_32', 'residue_32', 'residue_32', 'residue_35', 'residue_36', 'residue_43', 'residue_48', 'residue_49', 'residue_50', 'residue_57', 'residue_61', 'residue_61', 'residue_61', 'residue_62', 'residue_64', 'residue_65', 'residue_65', 'residue_65', 'residue_66', 'residue_66', 'residue_67', 'residue_67', 'residue_67'), 
             to = c('residue_189', 'residue_192', 'residue_193', 'residue_247', 'residue_251', 'residue_266', 'residue_268', 'residue_280', 'residue_281', 'residue_168', 'residue_189', 'residue_192', 'residue_336', 'residue_281', 'residue_336', 'residue_340', 'residue_365', 'residue_365', 'residue_366', 'residue_369', 'residue_168', 'residue_171', 'residue_178', 'residue_189', 'residue_76', 'residue_263', 'residue_265', 'residue_343', 'residue_358', 'residue_361', 'residue_362', 'residue_365', 'residue_343', 'residue_346', 'residue_347', 'residue_273', 'residue_274', 'residue_277', 'residue_274', 'residue_95', 'residue_93', 'residue_94', 'residue_95', 'residue_96', 'residue_95', 'residue_96', 'residue_98', 'residue_95', 'residue_96', 'residue_97', 'residue_98', 'residue_98', 'residue_97', 'residue_98', 'residue_99', 'residue_100', 'residue_100', 'residue_353', 'residue_79', 'residue_82', 'residue_100', 'residue_101', 'residue_102', 'residue_102', 'residue_79', 'residue_101', 'residue_102', 'residue_104', 'residue_76', 'residue_82', 'residue_93', 'residue_349', 'residue_349', 'residue_349', 'residue_95', 'residue_85', 'residue_95', 'residue_97', 'residue_82', 'residue_85', 'residue_82', 'residue_83', 'residue_85', 'residue_81', 'residue_82', 'residue_81', 'residue_82', 'residue_83'))
)
connect$value <- runif(nrow(connect))
 
#connect

# create a vertices data.frame. One line per object of our hierarchy
vertices <- data.frame(
  name = unique(c(as.character(edges$from), as.character(edges$to))),
  value = as.numeric(rep(1))
)
# Let's add a column with the group of each name. It will be useful later to color points
vertices$group <- edges$from[match(vertices$name, edges$to)]




#Let's add information concerning the label we are going to add: angle, horizontal adjustement and potential flip
#calculate the ANGLE of the labels
vertices$id <- NA
myleaves <- which(is.na( match(vertices$name, edges$from) ))
nleaves <- length(myleaves)
vertices$id[ myleaves ] <- seq(1:nleaves)
vertices$angle <- 90 - 360 * vertices$id / nleaves
 
# calculate the alignment of labels: right or left
# If I am on the left part of the plot, my labels have currently an angle < -90
vertices$hjust <- ifelse( vertices$angle < -90, 1, 0)
 
# flip angle BY to make them readable
vertices$angle <- ifelse(vertices$angle < -90, vertices$angle+180, vertices$angle)




# Create a graph object
mygraph <- igraph::graph_from_data_frame( edges, vertices=vertices )
 
# The connection object must refer to the ids of the leaves:
from  <-  match( connect$from, vertices$name)
to  <-  match( connect$to, vertices$name)
 



#CUSTOMIZATION

ggraph(mygraph, layout = 'dendrogram', circular = TRUE) + 
  geom_conn_bundle(data = get_con(from = from, to = to), alpha=0.5, width=1, aes(colour=..index..)) +

  geom_node_text(aes(x = x*1.15, y=y*1.15, filter = leaf, label=name, angle = angle, hjust=hjust, colour=group), size=2, alpha=1) +
  
  geom_node_point(aes(filter = leaf, x = x*1.07, y=y*1.07, colour=group, size=value, alpha=0.2)) +
  scale_colour_manual(values= rep( brewer.pal(9,"Paired") , 30)) +
  scale_size_continuous( range = c(0.1,10) ) +
  
  theme_void() +
  theme(
    legend.position="none",
    plot.margin=unit(c(1,6,0,1),"cm"),
  ) +
  expand_limits(x = c(-1.3, 1.3), y = c(-1.3, 1.3))


  
```
